on:
  push:
    branches:
      - main
  schedule:
    - cron: '45 17 * * *'


name: cron

jobs:
  cron:
    name: "my cron"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: |
          echo "Hello from ${{ github.repository }}!"
          ## echo "- in job ${{ job.name }}!"
          echo "- in response to ${{ github.event_name }}"
          echo "ran on $(hostname) under $(cat /etc/issue)"
          echo "ran at $(date)"
          echo "$(which python) $(python --version)"
          echo "as user $(whoami) with pwd $(pwd)"
      - name: decrypt secret
        run: |
          ./.github/scripts/decrypt.sh
          ls -l 
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: install python packages
        run: |
          pip install --no-input --user --upgrade google-api-python-client google-auth-oauthlib numpy datetime 
      - name: access spreadsheet
        run: ./test.py
      - name: commit to readme
        run: |
          git config --global user.name 'The Robot'
          git config --global user.email 'paciorek@users.noreply.github.com'
          git add README.md
          git commit -m "Automated readme update"
          git push
        
