on:
  push:
    branches:
      - main
  schedule:
    - cron: '45 17 * * *'


name: cron

jobs:
  cron:
    name: "my cron"
    runs-on: ubuntu-20.04
    steps:
      - name: first step
      - run: |
          echo "Hello from ${{ github.repository }}!"
          echo "- in job ${{ job.name }}!"
          echo "- in response to ${{ github.event_name }}"
          echo "ran on $(hostname) under $(cat /etc/issue)"
          echo "ran at $(date)"
