on:
  push:
    branches:
      - main
  schedule:
    - cron: '45 17 * * *'


name: cron

jobs:
  cron:
    name: "my cron"
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "Hello from ${{ github.event.name }}!"
          echo "- in ${{ github.event.jobs.cron.name }}!"
          echo "ran on $(hostname) under $(cat /etc/issue)"
          echo "ran at $(date)"
